version: '3.8'

services:
  cpm-server:
    container_name: cpm-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 9000:9000
    depends_on:
      - cpm-postgres

  cpm-postgres:
    container_name: cpm-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresVolume:/var/lib/postgresql/data

volumes:
  postgresVolume:
